-- Elmira/Display/TextureLibrary.lua — the visual texture library (AT4-D2).
--
-- PURE DATA AND PURE LOOKUPS. No frames, no WoW API, no `ns` reads: this file answers "which
-- textures may a player pick from, and what are they called", and nothing else. Who draws the grid
-- is Options/TexturePickerWidget.lua's business; whether WeakAuras is installed is the adapter's
-- (`Adapter.addonLoaded`), and arrives here as a PREDICATE rather than being asked for, which is
-- what keeps this file testable on its own and free of the client. The one category that is not
-- here is LibSharedMedia's, which is live rather than fixed and is assembled by
-- `Display/Textures.libraryGroups` from the library the player actually runs.
--
-- ------------------------------------------------------------------ where these paths come from
--
-- LICENCE FIRST (owner's decision, 2026-09-11). Elmira is MIT; WeakAuras and PowerAuras are GPL.
-- Not one of their files is copied into this repository and none ever will be: what is listed below
-- is a PATH, and a path is a fact about the client's own file system in the same way an item's
-- inventory slot is a fact about the item. Every WeakAuras or PowerAuras path is offered ONLY on a
-- character that already has WeakAuras installed -- we point at the player's own copy, we never
-- ship one. Every DISPLAY NAME here is ours: generated by `nameFromPath` below from the path's last
-- segment, or written here beside a numeric id. No name string was copied from anybody's list.
--
-- THE BLIZZARD ENTRIES ARE FILE IDs, not paths, and that is the client's doing rather than a choice
-- made here: Blizzard's own art is addressable by numeric file id, the 1.15 client accepts one
-- where it accepts a path (this is how every texture picker on this install feeds `SetTexture`),
-- and the ids below are exactly the ones that resolve on CLASSIC ERA.
--
-- THERE IS NO "BLIZZARD ALERTS" CATEGORY, and its absence is deliberate: the proc-overlay family
-- (the biggest and prettiest set on retail) is not in this client's data at all. WeakAuras on this
-- very install drops the whole group on Classic Era, along with 17 beams, 9 icons and 9 runes it
-- keeps elsewhere; those are dropped here too. Listing them would put ~120 empty cells in the
-- picker, which is this addon's characteristic defect -- something that looks like a feature and
-- draws nothing. Read off the live install 2026-09-11; no code and no name string came with them.
local ADDON, ns = ...
ns = ns or _G.__ELM_NS or {} -- mutants: equivalent tests/helper.lua always passes ns as a vararg

local TextureLibrary = {}

-- The addon whose files the last two categories point at. One constant, read by the category
-- definitions and by `requires` below, so "which addon does this need" is answered in one place.
local WEAKAURAS = "WeakAuras"

local ELMIRA_MEDIA = "Interface\\AddOns\\Elmira\\media\\"
local WA_MEDIA = "Interface\\AddOns\\WeakAuras\\Media\\Textures\\"
-- WeakAuras' own spelling of its PowerAuras folder ("Addons", not "AddOns"). WoW paths are
-- case-insensitive, so either loads; this one is what the files are actually referenced by.
local PA_MEDIA = "Interface\\Addons\\WeakAuras\\PowerAurasMedia\\Auras\\"
local PA_COUNT = 145            -- Aura1 … Aura145, counted on disk 2026-09-11

-- TextureLibrary.nameFromPath(path) -> a human name
--
-- OUR name for a file, built from the file's own last segment: extension dropped, `_`/`-` turned
-- into spaces, run-together words split at a lower-to-upper or letter-to-digit boundary, each word
-- given a capital -- so `Circle_AlphaGradient_In.tga` reads "Circle Alpha Gradient In" and
-- `PVP-Banner-Emblem-7` keeps its shouted PVP. A generated file name, never translated prose:
-- there is no locale in which `square_border_5px.tga` is a different file.
function TextureLibrary.nameFromPath(path)
  local tail = tostring(path or ""):match("([^\\/]+)$") or ""
  tail = tail:gsub("%.%a+$", "")
  tail = tail:gsub("[_%-]", " ")
  tail = tail:gsub("(%l)(%u)", "%1 %2")
  tail = tail:gsub("(%a)(%d)", "%1 %2")
  tail = tail:gsub("%s+", " ")
  tail = tail:gsub("^%s*(.-)%s*$", "%1")
  return (tail:gsub("%S+", function(word)
    local capitalised = word:gsub("^%l", string.upper)
    return capitalised
  end))
end

-- mutants: the return below is equivalent -- `add` is local (not exported); every caller uses it
-- only for the side effect on `out`, and none reads this return value.
local function add(out, path, name)
  out[#out + 1] = { path = path, name = name or TextureLibrary.nameFromPath(path) }
  return out -- mutants: equivalent see above
end

-- A run of numeric file ids under one heading. The id IS the whole path, so there is no segment to
-- generate a name from -- the category's own noun supplies the word and the id tells two of them
-- apart, which is all a name has to do beside a preview of the thing itself.
local function addIDs(out, noun, ids)
  for _, id in ipairs(ids) do add(out, id, noun .. " " .. id) end
  return out
end

-- ---------------------------------------------------------------- Elmira's own shapes

local ELMIRA = {}
for _, shape in ipairs({ "ring", "disc", "square", "diamond", "arrow", "star", "bar", "chevron" }) do
  add(ELMIRA, ELMIRA_MEDIA .. "shape_" .. shape, TextureLibrary.nameFromPath(shape))
end

-- ---------------------------------------------------------------- Blizzard's own art

-- Long thin art: chains, lightning, ropes, mana beams. Worth a category of its own because they are
-- the only entries here that want stretching rather than a square.
local BEAMS = addIDs({}, "Beam", {
  "186185", "186186", "186187", "186189", "186195", "186198", "186201", "186202", "186205",
  "186208", "186211", "186214",
})

-- Symbols: paw, feathers, eye, snowflake, shield, crossed swords…
local ICONS = addIDs({}, "Icon", {
  "165558", "165607", "165608", "165609", "165610", "165611", "165612", "166056", "166058",
  "166125", "166386", "166418", "166423", "166606", "166662", "166683", "166706", "166954",
  "166984",
})

-- The glyph circles the client draws under summoning and holy effects.
local RUNES = addIDs({}, "Rune", {
  "165630", "165631", "165634", "165635", "165638", "165639", "165640", "165881", "165927",
  "165928", "165929", "166341", "166748", "166749", "166750", "166757", "166979",
})

local SPARKS = addIDs({}, "Spark", { "130877" })

-- The PvP banner emblems: 1-7 at the top level and 2-101 under Icons\ (45 and 57 are not in the
-- client's data). A hundred-odd hand-drawn heraldic symbols -- the single largest supply of "a
-- clear shape at a glance" this client ships, which is exactly what an indicator needs to be.
local PVP = {}
for i = 1, 7 do
  add(PVP, "Interface\\PVPFrame\\PVP-Banner-Emblem-" .. i)
end
local NO_EMBLEM = { [45] = true, [57] = true }
for i = 2, 101 do
  if not NO_EMBLEM[i] then
    add(PVP, "Interface\\PVPFrame\\Icons\\PVP-Banner-Emblem-" .. i)
  end
end

-- The raid target icons -- star, circle, diamond… -- plus the combined sheet they are cut from.
-- Named for what a player calls them rather than for the file (`UI-RaidTargetingIcon_3` is a
-- diamond, which the file name does not say and this list does not pretend to know).
local MARKERS = {}
for i = 1, 8 do
  add(MARKERS, "Interface\\TargetingFrame\\UI-RaidTargetingIcon_" .. i, "Marker " .. i)
end
add(MARKERS, "Interface\\TargetingFrame\\UI-RaidTargetingIcons", "All Markers")

-- ---------------------------------------------------------------- WeakAuras', by path only

local WA_SHAPES = {}
for _, file in ipairs({
  "Circle_Smooth", "Circle_Smooth_Border", "Circle_Squirrel", "Circle_Squirrel_Border",
  "Circle_White", "Circle_White_Border", "Square_Smooth", "Square_Smooth_Border",
  "Square_Smooth_Border2", "Square_Squirrel", "Square_Squirrel_Border", "Square_White",
  "Square_White_Border", "Square_FullWhite", "Triangle45", "Trapezoid",
  "triangle-border.tga", "triangle.tga", "Circle_Smooth2.tga", "circle_border5.tga",
  "ring_glow3.tga", "square_mini.tga", "target_indicator.tga", "target_indicator_glow.tga",
  "arrows_target.tga", "Circle_AlphaGradient_In.tga", "Circle_AlphaGradient_Out.tga",
  "Ring_10px.tga", "Ring_20px.tga", "Ring_30px.tga", "Ring_40px.tga", "Square_AlphaGradient.tga",
  "square_border_1px.tga", "square_border_5px.tga", "square_border_10px.tga",
}) do
  add(WA_SHAPES, WA_MEDIA .. file)
end

-- All 145 in ONE category (owner, 2026-09-11): PowerAuras' own sub-grouping is somebody else's
-- editorial work, and reproducing it would be copying the one thing about this set that is not a
-- fact about the files.
local POWERAURAS = {}
for i = 1, PA_COUNT do
  add(POWERAURAS, PA_MEDIA .. "Aura" .. i)
end

-- ---------------------------------------------------------------- the categories
--
-- Ordered, because the picker's dropdown is drawn in this order and "which list was it in" is the
-- only thing a player remembers about 350 pictures. `requires` names the addon whose files a
-- category points at; nil means every client has them. `name` is a locale KEY, looked up by the
-- window that draws it -- this file holds no localisation of its own (it has no `L`), and the keys
-- live in the locale table with every other user-facing string.
TextureLibrary.GROUPS = {
  -- AT6-D2: "Shapes", not "Elmira Shapes" -- this is Elmira's own picker, so saying so twice in one
  -- dropdown says nothing. The WeakAuras group below keeps its addon's name, where it earns it.
  { key = "elmira",     name = "Shapes",           textures = ELMIRA },
  { key = "beams",      name = "Beams",            textures = BEAMS },
  { key = "icons",      name = "Icons",            textures = ICONS },
  { key = "pvp",        name = "PvP Emblems",      textures = PVP },
  { key = "runes",      name = "Runes",            textures = RUNES },
  { key = "sparks",     name = "Sparks",           textures = SPARKS },
  { key = "markers",    name = "Target Markers",   textures = MARKERS },
  { key = "weakauras",  name = "WeakAuras Shapes", textures = WA_SHAPES,  requires = WEAKAURAS },
  { key = "powerauras", name = "PowerAuras",       textures = POWERAURAS, requires = WEAKAURAS },
}

-- TextureLibrary.groups(isLoaded) -> every declared category, this character's own marked
--
-- `isLoaded(addonName)` is the caller's predicate -- `Display/Textures.addonLoaded` in the addon, a
-- plain function in a spec. TX1-D6 (owner): a category whose addon is not loaded is no longer
-- DROPPED -- it is handed back with `unavailable = <addon name>` instead, so the picker's Category
-- dropdown can still LIST it, greyed out with a reason, rather than making it look as if WeakAuras
-- simply has no shapes. A group that is available is the SAME table as in `GROUPS` (nothing here
-- ever copies a texture list); one that is not is a fresh table borrowing that same `textures`
-- field, so the shared definition itself never carries this session's own WeakAuras state.
function TextureLibrary.groups(isLoaded)
  local out = {}
  for _, group in ipairs(TextureLibrary.GROUPS) do
    if not group.requires or (isLoaded and isLoaded(group.requires) == true) then
      out[#out + 1] = group
    else
      out[#out + 1] = {
        key = group.key, name = group.name, textures = group.textures,
        requires = group.requires, unavailable = group.requires,
      }
    end
  end
  return out
end

-- TextureLibrary.requires(path) -> the addon this path needs, or nil
--
-- Pure prefix test, not a lookup in the lists above: a path a player typed, or one stored before
-- they uninstalled WeakAuras, is exactly the case AT4-D3 is about and it may be in no category at
-- all. Case-insensitive, because `Interface\AddOns\…` and `Interface\Addons\…` are the same folder
-- to the client and both spellings are in circulation (WeakAuras itself uses both).
function TextureLibrary.requires(path)
  local lowered = tostring(path or ""):lower():gsub("/", "\\")
  if lowered:find("interface\\addons\\weakauras\\", 1, true) == 1 then return WEAKAURAS end
  return nil -- mutants: equivalent the last statement of a function; Lua returns nil either way
end

-- TextureLibrary.drawable(path) -> what `SetTexture` wants
--
-- A Blizzard entry is a numeric FILE ID and has to arrive at the client as a number; a path arrives
-- as a string. One conversion, in one place, so the indicator and the picker can never disagree
-- about which of the two a stored value is -- an id passed as a string draws nothing at all, which
-- is the exact failure this channel already falls back to the ring for.
function TextureLibrary.drawable(path)
  return tonumber(path) or path
end

-- TextureLibrary.matches(name, needle) -> does this entry answer the picker's search box
--
-- Plain case-insensitive substring, never a pattern: a player typing `circle_` is typing part of a
-- file name, and `-` and `%` in a Lua pattern would either error or quietly match nothing.
function TextureLibrary.matches(name, needle)
  if needle == nil or needle == "" then return true end
  return tostring(name or ""):lower():find(tostring(needle):lower(), 1, true) ~= nil
end

ns.TextureLibrary = TextureLibrary
return TextureLibrary
